//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmdb_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class awis_site
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public awis_site()
        {
            this.urls = new HashSet<url>();
            this.disc_url = new HashSet<disc_url>();
        }
    
        public long id { get; set; }
        public string TLD { get; set; }
        public System.DateTime as_of_utc { get; set; }
        public bool adult { get; set; }
        public string title { get; set; }
        public string desc { get; set; }
        public string lang { get; set; }
        public string url { get; set; }
        public Nullable<long> awis_cat_id { get; set; }
        public Nullable<bool> hard_disallow { get; set; }
        public bool exclude_terms_like_site_title { get; set; }
        public string logo_file_name { get; set; }
    
        public virtual awis_cat awis_cat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<url> urls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<disc_url> disc_url { get; set; }
    }
}
