//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmdb_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbip_city_2016_11
    {
        public long id { get; set; }
        public string ipFrom { get; set; }
        public string ipTo { get; set; }
        public string countryCode { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public Nullable<long> ipFromNum { get; set; }
        public Nullable<long> ipToNum { get; set; }
    }
}
