//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmdb_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class disc_url_cwc
    {
        public long id { get; set; }
        public Nullable<long> disc_url_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string desc { get; set; }
        public string href { get; set; }
    
        public virtual disc_url disc_url { get; set; }
    }
}
