//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmdb_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class disc_term
    {
        public long id { get; set; }
        public long term_id { get; set; }
        public System.DateTime search_utc { get; set; }
        public int added_count { get; set; }
        public string desc { get; set; }
    
        public virtual term term { get; set; }
    }
}
