//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmdb_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class disc_url
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public disc_url()
        {
            this.disc_url_cwc = new HashSet<disc_url_cwc>();
            this.disc_url_html = new HashSet<disc_url_html>();
            this.disc_url_osl = new HashSet<disc_url_osl>();
        }
    
        public long id { get; set; }
        public string url { get; set; }
        public string meta_title { get; set; }
        public System.DateTime discovered_at_utc { get; set; }
        public string img_url { get; set; }
        public long main_term_id { get; set; }
        public Nullable<long> term_id { get; set; }
        public int search_num { get; set; }
        public bool suggested_topic { get; set; }
        public int result_num { get; set; }
        public int term_num { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string desc { get; set; }
        public int url_hash { get; set; }
        public Nullable<long> awis_site_id { get; set; }
        public string status { get; set; }
        public string from { get; set; }
        public long results_count { get; set; }
    
        public virtual awis_site awis_site { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<disc_url_cwc> disc_url_cwc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<disc_url_html> disc_url_html { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<disc_url_osl> disc_url_osl { get; set; }
        public virtual term term { get; set; }
        public virtual term term1 { get; set; }
    }
}
