//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmdb_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class golden_term
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public golden_term()
        {
            this.url_golden_term = new HashSet<url_golden_term>();
        }
    
        public long id { get; set; }
        public long parent_term_id { get; set; }
        public long child_term_id { get; set; }
        public int mmcat_level { get; set; }
        public Nullable<System.DateTime> autosuggested_at_utc { get; set; }
        public Nullable<long> url_id { get; set; }
        public bool from_wiki { get; set; }
    
        public virtual term term { get; set; }
        public virtual term term1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<url_golden_term> url_golden_term { get; set; }
        public virtual url url { get; set; }
    }
}
