//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmdb_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class gt_parent
    {
        public long id { get; set; }
        public long child_term_id { get; set; }
        public long parent_term_id { get; set; }
        public double S_norm { get; set; }
        public double S { get; set; }
    
        public virtual term term { get; set; }
        public virtual term term1 { get; set; }
    }
}
