//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmdb_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class gt_path_to_root
    {
        public long id { get; set; }
        public long term_id { get; set; }
        public int path_no { get; set; }
        public int seq { get; set; }
        public long seq_term_id { get; set; }
    
        public virtual term term { get; set; }
        public virtual term term1 { get; set; }
    }
}
