//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmdb_model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mm02Entities : DbContext
    {
        public mm02Entities()
            : base("name=mm02Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<awis_site> awis_site { get; set; }
        public virtual DbSet<awis_cat> awis_cat { get; set; }
        public virtual DbSet<term_type> term_type { get; set; }
        public virtual DbSet<cal_entity_type> cal_entity_type { get; set; }
        public virtual DbSet<term_matrix> term_matrix { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_url> user_url { get; set; }
        public virtual DbSet<url_golden_term> url_golden_term { get; set; }
        public virtual DbSet<term> terms { get; set; }
        public virtual DbSet<golden_term> golden_term { get; set; }
        public virtual DbSet<url> urls { get; set; }
        public virtual DbSet<wiki_page> wiki_page { get; set; }
        public virtual DbSet<wiki_catlink> wiki_catlink { get; set; }
        public virtual DbSet<url_term> url_term { get; set; }
    }
}
