//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmdb_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class share
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public share()
        {
            this.share_active = new HashSet<share_active>();
        }
    
        public long id { get; set; }
        public string share_code { get; set; }
        public long source_user_id { get; set; }
        public System.DateTime created_utc { get; set; }
        public Nullable<long> url_id { get; set; }
        public Nullable<long> topic_id { get; set; }
        public bool share_all { get; set; }
        public Nullable<long> target_user_id { get; set; }
        public string target_user_ref { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<share_active> share_active { get; set; }
        public virtual term term { get; set; }
        public virtual url url { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
