//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmdb_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class share_active
    {
        public long id { get; set; }
        public long share_id { get; set; }
        public long user_id { get; set; }
        public System.DateTime accepted_utc { get; set; }
    
        public virtual share share { get; set; }
        public virtual user user { get; set; }
    }
}
