//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmdb_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class term
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public term()
        {
            this.term_matrix = new HashSet<term_matrix>();
            this.term_matrix1 = new HashSet<term_matrix>();
            this.url_term = new HashSet<url_term>();
            this.golden_term = new HashSet<golden_term>();
            this.golden_term1 = new HashSet<golden_term>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public int term_type_id { get; set; }
        public Nullable<int> cal_entity_type_id { get; set; }
        public long occurs_count { get; set; }
    
        public virtual cal_entity_type cal_entity_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<term_matrix> term_matrix { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<term_matrix> term_matrix1 { get; set; }
        public virtual term_type term_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<url_term> url_term { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<golden_term> golden_term { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<golden_term> golden_term1 { get; set; }
    }
}
