
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mmdb_model
{

using System;
    using System.Collections.Generic;
    
public partial class term_matrix
{

    public long id { get; set; }

    public long term_a_id { get; set; }

    public long term_b_id { get; set; }

    public long occurs_together_count { get; set; }



    public virtual term term { get; set; }

    public virtual term term1 { get; set; }

}

}
