//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmdb_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class url
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public url()
        {
            this.shares = new HashSet<share>();
            this.url_parent_term = new HashSet<url_parent_term>();
            this.url_term = new HashSet<url_term>();
            this.user_url = new HashSet<user_url>();
            this.url_text = new HashSet<url_text>();
        }
    
        public long id { get; set; }
        public string url1 { get; set; }
        public Nullable<System.DateTime> calais_as_of_utc { get; set; }
        public long awis_site_id { get; set; }
        public string cal_lang { get; set; }
        public string meta_title { get; set; }
        public string meta_all { get; set; }
        public Nullable<System.DateTime> processed_at_utc { get; set; }
        public int processed_golden_count { get; set; }
        public int unmapped_wiki_terms { get; set; }
        public int mapped_wiki_terms { get; set; }
        public string img_url { get; set; }
        public Nullable<int> nlp_suitability_score { get; set; }
        public int disambig_wiki_terms { get; set; }
        public double W { get; set; }
        public int W_n { get; set; }
        public string url_hash { get; set; }
        public string raw_text { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<share> shares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<url_parent_term> url_parent_term { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<url_term> url_term { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_url> user_url { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<url_text> url_text { get; set; }
        public virtual awis_site awis_site { get; set; }
    }
}
