//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmdb_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class url
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public url()
        {
            this.url_term = new HashSet<url_term>();
            this.user_url = new HashSet<user_url>();
        }
    
        public long id { get; set; }
        public string url1 { get; set; }
        public Nullable<System.DateTime> calais_as_of_utc { get; set; }
        public long awis_site_id { get; set; }
        public string cal_lang { get; set; }
        public string meta_title { get; set; }
        public string meta_all { get; set; }
    
        public virtual awis_site awis_site { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<url_term> url_term { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_url> user_url { get; set; }
    }
}
