
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mmdb_model
{

using System;
    using System.Collections.Generic;
    
public partial class url_term
{

    public long id { get; set; }

    public long url_id { get; set; }

    public long term_id { get; set; }

    public Nullable<double> cal_topic_score { get; set; }

    public Nullable<int> cal_socialtag_importance { get; set; }

    public Nullable<double> cal_entity_relevance { get; set; }

    public Nullable<double> wiki_S { get; set; }

    public string candidate_reason { get; set; }

    public Nullable<double> tss { get; set; }

    public Nullable<double> tss_norm { get; set; }

    public Nullable<double> S { get; set; }



    public virtual term term { get; set; }

    public virtual url url { get; set; }

}

}
