
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mmdb_model
{

using System;
    using System.Collections.Generic;
    
public partial class url_parent_term
{

    public long id { get; set; }

    public long url_id { get; set; }

    public long term_id { get; set; }

    public int pri { get; set; }

    public bool suggested_dynamic { get; set; }

    public bool found_topic { get; set; }

    public Nullable<double> S { get; set; }

    public Nullable<double> avg_S { get; set; }

    public Nullable<double> S_norm { get; set; }

    public int min_d_paths_to_root_url_terms { get; set; }

    public int max_d_paths_to_root_url_terms { get; set; }

    public double perc_ptr_topics { get; set; }

    public int mmtopic_level { get; set; }

    public double avg_TSS_leaf { get; set; }

    public bool url_title_topic { get; set; }



    public virtual term term { get; set; }

    public virtual url url { get; set; }

}

}
