
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mmdb_model
{

using System;
    using System.Collections.Generic;
    
public partial class url_text
{

    public long id { get; set; }

    public long url_id { get; set; }

    public string raw_text { get; set; }

    public System.DateTime as_of_utc { get; set; }



    public virtual url url { get; set; }

}

}
