//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmdb_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class url_golden_term
    {
        public long id { get; set; }
        public long url_id { get; set; }
        public long golden_term_id { get; set; }
        public int rank { get; set; }
        public System.DateTime datetime_utc { get; set; }
    
        public virtual golden_term golden_term { get; set; }
        public virtual url url { get; set; }
    }
}
