//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmdb_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_url
    {
        public long id { get; set; }
        public long userId { get; set; }
        public long urlId { get; set; }
        public System.DateTime navUtc { get; set; }
        public int im_score { get; set; }
    
        public virtual url url { get; set; }
        public virtual user user { get; set; }
    }
}
