//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmdb_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_url_classification
    {
        public long id { get; set; }
        public long user_url_id { get; set; }
        public long term_id { get; set; }
        public short pri { get; set; }
        public long user_id { get; set; }
        public bool reused { get; set; }
    
        public virtual user_url user_url { get; set; }
        public virtual user user { get; set; }
        public virtual term term { get; set; }
    }
}
