//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmdb_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_url
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_url()
        {
            this.user_url_classification = new HashSet<user_url_classification>();
        }
    
        public long id { get; set; }
        public long userId { get; set; }
        public long urlId { get; set; }
        public System.DateTime navUtc { get; set; }
        public Nullable<double> im_score { get; set; }
        public Nullable<int> audible_pings { get; set; }
        public Nullable<long> time_on_tab { get; set; }
    
        public virtual url url { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_url_classification> user_url_classification { get; set; }
        public virtual user user { get; set; }
    }
}
