
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mmdb_model
{

using System;
    using System.Collections.Generic;
    
public partial class wiki_page
{

    public long page_id { get; set; }

    public int page_namespace { get; set; }

    public string page_title { get; set; }

    public Nullable<int> processed_to_depth { get; set; }

}

}
