//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmdb_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class wiki_catlink
    {
        public long cl_from { get; set; }
        public string cl_to { get; set; }
        public string cl_type { get; set; }
        public System.Guid id { get; set; }
        public Nullable<bool> processed { get; set; }
    }
}
