//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mm_wikidb
{
    using System;
    using System.Collections.Generic;
    
    public partial class page
    {
        public long page_id { get; set; }
        public int page_namespace { get; set; }
        public byte[] page_title { get; set; }
        public byte[] page_restrictions { get; set; }
        public decimal page_counter { get; set; }
        public bool page_is_redirect { get; set; }
        public bool page_is_new { get; set; }
        public byte[] page_touched { get; set; }
        public byte[] page_links_updated { get; set; }
        public long page_latest { get; set; }
        public long page_len { get; set; }
        public byte[] page_content_model { get; set; }
        public byte[] page_lang { get; set; }
    }
}
