USE [master]
GO

/****** Object:  Database [mm02]    Script Date: 24 Jul 2016 11:08:43 AM ******/
CREATE DATABASE [mm02]
GO

ALTER DATABASE [mm02] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [mm02].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [mm02] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [mm02] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [mm02] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [mm02] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [mm02] SET ARITHABORT OFF 
GO

ALTER DATABASE [mm02] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [mm02] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [mm02] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [mm02] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [mm02] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [mm02] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [mm02] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [mm02] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [mm02] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [mm02] SET  ENABLE_BROKER 
GO

ALTER DATABASE [mm02] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [mm02] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [mm02] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [mm02] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [mm02] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [mm02] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [mm02] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [mm02] SET RECOVERY FULL 
GO

ALTER DATABASE [mm02] SET  MULTI_USER 
GO

ALTER DATABASE [mm02] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [mm02] SET DB_CHAINING OFF 
GO

ALTER DATABASE [mm02] SET QUERY_STORE = OFF
GO

USE [mm02]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [mm02] SET  READ_WRITE 
GO

